# : replace the title with the name of your restaurant!
title: "Habesha Delights! 🇪🇹"
# : write your restaurateur alter ego name below, or your own name
author: Naboni Thomas
# : write your Google Analytics tracking ID below
google_analytics: G-72Y7WS934L

theme: minima

collections:
  explorations:
    output: true
